#######################################################
## @author   Md. Emran Hossain                       ##
## @version  1.0                                     ##
## @since    20 Jan, 2022                            ##
#######################################################

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:postgresql://localhost:5432/report-service
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver


logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: ERROR
    com:
      synesisit:
        lnm: info
  file:
    name: C:/log/report-service/app.log
    max-size: 10MB
    max-history: 0
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"